create table tb_sales (amount float(53), date date, deals integer, visited integer, id bigint generated by default as identity, seller_id bigint, primary key (id));
create table tb_sellers (id bigint generated by default as identity, email varchar(255), level varchar(255), name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;
