
    create table tb_sales (
        amount float(53),
        date date,
        deals integer,
        visited integer,
        id bigint generated by default as identity,
        seller_id bigint,
        primary key (id)
    );

    create table tb_sellers (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table if exists tb_sale 
       add constraint FKo5hwoldon8fywrih2luf0n7hu 
       foreign key (seller_id) 
       references tb_sellers;
